services:
    # Reverse proxy.
    caddy:
        container_name: caddy
        image: caddy:2.8
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        networks:
            - caddy
            - markdorf
            - dev
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
            # instance markdorf
            - ./data/markdorf/static:/www/markdorf/static
            - ./data/markdorf/media:/www/markdorf/media
            # instance dev
            - ./data/dev/static:/www/dev/static
            - ./data/dev/media:/www/dev/media
        env_file:
            - ./caddy/caddy.env

    # instance markdorf
    markdorf:
        container_name: markdorf
        #image: ghcr.io/wahlrechner/wahlrechner:latest
        build:
            context: ../wahlrechner
        command: bash -c 'docker/wait-for-it/wait-for-it.sh db_markdorf:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        networks:
            - markdorf
            - db_markdorf
        volumes:
            - ./data/markdorf/static:/code/assets/
            - ./data/markdorf/media:/code/media/
            - ./data/markdorf/logs/wahlrechner:/code/logs/
            - ./data/markdorf/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./data/markdorf/stats:/code/wahlrechner/stats
            - ./themes:/code/themes
        env_file:
            - ./config/config.env
            - ./config/config_markdorf.env
        depends_on:
            - db_markdorf

    db_markdorf:
        container_name: db_markdorf
        image: mariadb
        restart: always
        networks:
            - db_markdorf
        env_file:
            - ./config/config.env
            - ./config/config_markdorf.env
        volumes:
            - ./data/markdorf/mysql:/var/lib/mysql

    # instance markdorf
    dev:
        container_name: dev
        #image: ghcr.io/wahlrechner/wahlrechner:latest
        build:
            context: ../wahlrechner
        command: bash -c 'docker/wait-for-it/wait-for-it.sh db_dev:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        networks:
            - dev
            - db_dev
        volumes:
            - ./data/dev/static:/code/assets/
            - ./data/dev/media:/code/media/
            - ./data/dev/logs/wahlrechner:/code/logs/
            - ./data/dev/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./data/dev/stats:/code/wahlrechner/stats
            - ./themes:/code/themes
        env_file:
            - ./config/config.env
            - ./config/config_dev.env
        depends_on:
            - db_dev

    db_dev:
        container_name: db_dev
        image: mariadb
        restart: always
        networks:
            - db_dev
        env_file:
            - ./config/config.env
            - ./config/config_dev.env
        volumes:
            - ./data/dev/mysql:/var/lib/mysql

volumes:
    caddy_data:
    caddy_config:

networks:
    caddy:
      name: caddy
    # instance dev
    db_dev:
    dev:
    # instance markdorf
    db_markdorf:
    markdorf:
