version: "3"

services:
    wahlrechner:
        container_name: wahlrechner
        image: ghcr.io/wahlrechner/wahlrechner:latest
#        build:
#            context: web/wahlrechner
        command: bash -c 'docker/wait-for-it/wait-for-it.sh db:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        networks:
            - wahlrechner_default
        volumes:
            - ./data/static:/code/assets/
            - ./data/media:/code/media/
            - ./data/logs/wahlrechner:/code/logs/
            - ./data/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./themes:/code/themes
            - ./data/stats:/code/wahlrechner/stats
        env_file:
            - ./config/config.env
        depends_on:
            - db

    db:
        container_name: db
        image: mariadb
        restart: always
        networks:
            - wahlrechner_default
        ports:
            - "3306:3306"
        env_file:
            - ./config/config.env
        volumes:
            - ./data/mysql:/var/lib/mysql

    caddy:
        container_name: caddy
        image: caddy:2.8
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        networks:
            - wahlrechner_default
            - caddy
        volumes:
            - ./web/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./data/static:/wahlrechner/static
            - ./data/media:/wahlrechner/media
            - caddy_data:/data
            - caddy_config:/config
        env_file:
            - ./web/caddy/caddy.env
        # volumes:
        #     - ./web/cert:/wahlrechner/cert
        #     - ./data/logs/apache:/usr/local/apache2/logs
        #     - /etc/letsencrypt:/etc/letsencrypt

volumes:
    caddy_data:
    caddy_config:

networks:
    wahlrechner_default:
    caddy:
      name: caddy
