version: "3"

services:
    wahlrechner:
        container_name: wahlrechner
        image: ghcr.io/wahlrechner/wahlrechner:latest
        command: bash -c 'docker/wait-for-it/wait-for-it.sh db:3306 -t 120 -- docker/startup-production.sh'
        restart: always
        volumes:
            - ./data/static:/code/assets/
            - ./data/logs/wahlrechner:/code/logs/
            - ./data/migrations/wahlrechner:/code/wahlrechner/migrations
            - ./config/design/templates:/code/wahlrechner/templates/custom
            - ./config/design/static:/code/static/custom
        env_file:
            - ./config/config.env
        depends_on:
            - db

    db:
        container_name: db
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - ./config/config.env
        volumes:
            - ./data/mysql:/var/lib/mysql

    web:
        container_name: web
        build:
            context: web/apache
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/static:/wahlrechner/static
            - ./web/cert:/wahlrechner/cert
            - ./data/logs/apache:/usr/local/apache2/logs
            - /etc/letsencrypt:/etc/letsencrypt
